### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by jmoseley** [r0adkll/upload-google-play#1]
I'm seeing the following error when running the action, this happens anywhere from 5 to 10 minutes after the action starts and there is no output.

```
##[error]request to https://www.googleapis.com/upload/androidpublisher/v3/applications/com.seiclo.maintenance/edits/15891608883389294376/bundles?uploadType=media failed, reason: socket hang up
##[error]Node run failed with exit code 1
```

Here is my work flow:

```
name: Build and Upload APK

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
      - '.github/workflows/build_upload_app_apk.yml'

jobs:
  build:
    name: build and upload apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install/Run GQL Gen
        env:
          GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
        run: yarn
        working-directory: app
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.x'
      - name: write keystore
        run: echo $GOOGLE_PLAY_KEY_JKS | base64 -d > $HOME/key.jks
        env:
          GOOGLE_PLAY_KEY_JKS: ${{ secrets.GOOGLE_PLAY_KEY_JKS }}
      - name: install flutter dependencies
        run: cd app && flutter pub get
      - name: build_runner
        run: cd app && flutter pub run build_runner build
      - name: build appbundle
        run: cd app && flutter build appbundle --release --target lib/main_release.dart
        env:
          GOOGLE_PLAY_KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_KEYSTORE_PASSWORD }}
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v1
        with:
          name: appbundle
          path: app/build/app/outputs/bundle/release/app.aab
  upload:
    name: upload bundle
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: appbundle
          path: ./app.aab
      - name: download private key
        run: echo $GOOGLE_SERVICE_ACCOUNT_JSON > ./private_key.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./private_key.json
          packageName: com.seiclo.maintenance
          releaseFile: ./app.aab
          track: alpha
          # mappingFile: app/build/outputs/mapping/release/mapping.txt
```

The app bundle is building correctly and being uploaded as an artifact.

Any ideas would be greatly appreciated.

**Comment by jmoseley** [comment]
I figured it out. The artifact downloads a folder, not just the file. I needed to specify the artifact download to a folder:

```
- uses: actions/download-artifact@v1
        with:
          name: appbundle
          path: ./app
```

and then reference the file:

```
- uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./private_key.json
          packageName: com.seiclo.maintenance
          releaseFile: ./app/app.aab
          track: alpha
          # mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Comment by r0adkll** [comment]
I'm glad you were able to fix your issue. I can probably implement better guards to prevent the action from hanging by adding checks to the input files to make sure they exist first.

**Comment by nirmalhk7** [comment]
I'm sorry, but I'm facing the same issue and I really can't figure where I've gone wrong.
```
name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository2
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Read project version code
      id: read_property_code
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './app/version.properties'
        property: 'version.code'
    - name: Read project version name
      id: read_property_name
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './app/version.properties'
        property: 'version.name'
    # - name: Run Unit Test
    #   id: tests
    #   run: ./gradlew test
    - name: Build AAB
      id: buildRelease
      run: ./gradlew bundleRelease
    - name: Sign AAB
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.KEYSTORE_V2 }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - name: Upload AAB
      id: uploadArtifact
      uses: actions/upload-artifact@v1
      with:
          name: appBundle
          path: app/build/outputs/bundle/release/app-release.aab
  
  deploy:
    name: Deploy Android App
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Retreive artifacts from Build stage
      uses: actions/download-artifact@v2
      with:
        name: appBundle
        path: app/build/outputs/bundle/release/app-release.aab
    - name: List Production Files
      run: ls app/build/outputs/bundle/release
    - name: Deploy to Play Store (PRODUCTION)
      id: deploy
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: com.nirmalhk7.collegego
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: production
```

Every stage in both jobs are able to run without errors. I used the List Production File stage to verify whether my file location is correct or not.
Here's the output for the last two stages of last jobs:
```
List Production Files
app-release.aab
Run ls app/build/outputs/bundle/release
  ls app/build/outputs/bundle/release
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
app-release.aab
```
```
  Deploy to Play Store (PRODUCTION)- 4m 1s
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: service_account.json
    packageName: com.nirmalhk7.collegego
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: production
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
##[error]request to https://www.googleapis.com/upload/androidpublisher/v3/applications/com.nirmalhk7.collegego/edits/02478717223293763578/bundles?uploadType=media failed, reason: socket hang up

```
