### ISSUE TITLE
Unable to find any release file  

### ISSUE THREAD

**Issue by ssepulveda08** [r0adkll/upload-google-play#100]
When I try to launch the workflows I get this error: 
Unable to find any release file @ app/build/outputs/bundle/release/app-release.aab

     ` uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # 3
          packageName: MyPackage
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
          mappingFile: mapping.txt`
          

already tried changing releaseFiles with:  ` releaseFiles: app/build/outputs/bundle/release/*.aab` but it doesn't work either

**Comment by markdturner** [comment]
This looks the same as #90 and I also have the same problem. From that other issue, I have tried setting the path in absolute and relative terms but no joy.

```yaml
releaseFiles: ./build/app/outputs/apk/release/*.apk'
```
```yaml
releaseFiles: ${{ github.workspace }}/build/app/outputs/apk/release/*.apk'
```

the path is correct as I can use it to add artefacts to the repo in a subsequent step
```yaml
- name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk'
```
