### ISSUE TITLE
Rollout is not executed

### ISSUE THREAD

**Issue by campovski** [r0adkll/upload-google-play#104]
**Describe the bug**
The build gets updated and a new release is created, although not rolled out. I need to manually go to Play Console Internal track and rollout the test release. Because the app is in draft, the only `status` I can use is `draft`.

**Workflow Step Configuration**

```yml
- name: Upload app bundle to Internal test track
   uses: r0adkll/upload-google-play@v1
   with:
     serviceAccountJson: service_account.json
     packageName: pkgname
     releaseFiles: build/app/outputs/bundle/release/app-release.aab
     track: internal
     status: draft
     inAppUpdatePriority: 5
     whatsNewDirectory: whatsnewdir
     mappingFile: build/app/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
