### ISSUE TITLE
Account Service Roles & Permissions

### ISSUE THREAD

**Issue by DPigeon** [r0adkll/upload-google-play#12]
Hello,

I am trying to use this action and I am unable to determine which role I need to set for my account service to authorize the deployment. I know that I have a role or permission with Android because I always get the `##[error]The caller does not have permission`. Even with all the roles set below:
![dddd](https://user-images.githubusercontent.com/37888675/84620010-cdde7800-aea4-11ea-8c71-9cc74d717b4b.png)

My permission is set to the Release Manager.
I am unable to upload anything to the Play Store. 

Any help would be appreciated. Here is my workflow:
```
 - name: Upload
      uses: r0adkll/upload-google-play@v1.0.4
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
        packageName: com.app
        releaseFile: app.apk
        track: beta
        userFraction: 0.15
```
