### ISSUE TITLE
Error: Invalid value at 'track_config.releases[0].status'

### ISSUE THREAD

**Issue by valeriyo** [r0adkll/upload-google-play#127]
Why?
```
Creating a new Edit for this release
Validating track 'internal'
Uploading ./artifacts/com.example.app-release.aab
Successfully uploaded 1 artifacts
Adding 1 artifacts to release on 'internal' track
Error: Invalid value at 'track_config.releases[0].status' (type.googleapis.com/google.play.publishingapi.v3.Release.Status), ""
```

```yml
      - uses: r0adkll/upload-google-play@v1
        with:
          track: internal
          packageName: com.example.app
          releaseFiles: ./artifacts/com.example.app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
```
