### ISSUE TITLE
joing

### ISSUE THREAD

**Issue by KingSkyros** [r0adkll/upload-google-play#128]
**Describe the bug**

**Workflow Step Configuration**

```yml
- name: Al-amin Faisal
  uses: KingSkyro
  with:
    serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: production
    whatsNewDirectory: distribution/whatsnew/
    mappingFile: app/build/outputs/mapping/release/mapping.txt 
   message: hello can I joining you in this.
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
