### ISSUE TITLE
Error assigning some value with $

### ISSUE THREAD

**Issue by Hacybeyker** [r0adkll/upload-google-play#131]
**Describe the bug**
Hello.
I have a problem because I have assigned a secret in an ENV and when I try to access it through `$` as in this case `$PACKAGE` for some reason does not get the value but if I access the secret directly in this way `${{ secret.PACKAGE }}` it works well.
It could support this since secrets are sometimes assigned as global ENVs to be accessed directly with the `$`

**Workflow Step Configuration**

```yml

env:
  PACKAGE: ${{ secrets.PACKAGE }}
. 
.
.
      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: ${{ secrets.SIGNING_SERVICE_ACCOUNT }}
          packageName: $PACKAGE
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: beta
```

When you try to assign this:
`packageName: $PACKAGE`
I get this error:
`Error: Invalid package name: $PACKAGE.`

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
