### ISSUE TITLE
Error: APK has the wrong package name. 

### ISSUE THREAD

**Issue by Sam2much96** [r0adkll/upload-google-play#141]
**Describe the bug**
I have verified with adb that the package name is valid but i keep on getting these errors
Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
Validating track 'beta'
Uploading ./source_code.apk
Error: Error: APK has the wrong package name.
Error: APK has the wrong package name.

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: production
    whatsNewDirectory: distribution/whatsnew/
    mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
Validating track 'beta'
Uploading ./source_code.apk
Error: Error: APK has the wrong package name.
Error: APK has the wrong package name.
