### ISSUE TITLE
Authenticate with Google Workload Identity Federation / OpenID Connect

### ISSUE THREAD

**Issue by rich-j** [r0adkll/upload-google-play#146]
Please support authenticating with the Google recommended [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) instead of using a Cloud Service Account Key JSON secret text/file. Github supports it as [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)

Google has created a Github Action [auth](https://github.com/google-github-actions/auth) that establishes the authentication session with Google Cloud. We are now using this for our deployments to Google Cloud using the action [setup-gcloud](https://github.com/google-github-actions/setup-gcloud). It works great - no more secrets needed.

**Comment by StuClift** [comment]
This is already supported as the auth writes the credentials file by default:
```yml
- id: auth
  uses: google-github-actions/auth@v0
  with:
    workload_identity_provider: <provider>
    service_account: <service-account>
- uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
```
