### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by arifinreinaldo** [r0adkll/upload-google-play#147]
**Describe the bug**
Unfortunately, I can't find a way to debug what is missing. Can you show me how to check the error

**Workflow Step Configuration**

```yml
- name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_DASHBOARD_JSON }}
        packageName: com.b2b.online
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: beta
        status: completed
        inAppUpdatePriority: 5
        userFraction: 0.99
        whatsNewDirectory: distribution/whatsnew
        mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [x ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

##[debug]Evaluating condition for step: 'Deploy to Play Store'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy to Play Store
##[debug]Loading inputs
##[debug]Evaluating: secrets.PLAY_DASHBOARD_JSON
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'PLAY_DASHBOARD_JSON'
##[debug]=> '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Result: '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Loading env
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ***
    packageName: com.b2b.online
    releaseFiles: app/build/outputs/bundle/release/app-release.aab
    track: beta
    status: completed
    inAppUpdatePriority: 5
    userFraction: 0.99
    whatsNewDirectory: distribution/whatsnew
    mappingFile: app/build/outputs/mapping/release/mapping.txt
  env:
    FIREBASE_TOKEN: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-1/x[64](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:64)
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-1/x64
    SIGNED_RELEASE_FILE: app/build/outputs/bundle/release/app-release.aab
##[debug]Finding files app/build/outputs/bundle/release/app-release.aab
Creating a new Edit for this release
Validating track 'beta'
Uploading app/build/outputs/bundle/release/app-release.aab
##[debug][1527487436472494[65](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:65)25, packageName=com.b2b.online]: Uploading App Bundle @ app/build/outputs/bundle/release/app-release.aab
##[debug][[15](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:15)2748743647[24](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:24)9465[25](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:25), versionCode=6, packageName=com.b2b.online]: Uploading Proguard mapping file @ app/build/outputs/mapping/release/mapping.txt
Successfully uploaded 1 artifacts
Adding 1 artifacts to release on 'beta' track
##[debug]Creating Track Release for Edit(15[27](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:27)4874[36](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:36)47249[46](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:46)[52](https://github.com/arifinreinaldo/b2b-simplr/actions/runs/3202122021/jobs/5230783797#step:9:52)5) for Track(beta) with a UserFraction(0.99), Status(completed), and VersionCodes(6)
##[debug]Found files: whatsnew-en-US
##[debug]Matches for whatsnew-en-US = whatsnew-en-US,en-US
Error: EISDIR: illegal operation on a directory, read
##[debug]Node Action run completed with exit code 1
##[debug]GOOGLE_APPLICATION_CREDENTIALS='./serviceAccountJson.json'
##[debug]Finishing: Deploy to Play Store
