### ISSUE TITLE
Release `v1` does not fetch the latest version

### ISSUE THREAD

**Issue by tk-nguyen** [r0adkll/upload-google-play#148]
Hello, I ran into the same issue as https://github.com/r0adkll/upload-google-play/issues/132, even after the update. 

```yml
- name: Deploy the app to the Play Store
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ***
    packageName: ***
    releaseFiles: "build/app/outputs/bundle/release/app-release.aab"
    track: beta
    status: completed
    changesNotSentForReview: true
```

Maybe I need to pin it to the exact version?
