### ISSUE TITLE
Support expanding environment variables in inputs

### ISSUE THREAD

**Issue by marianhlavac** [r0adkll/upload-google-play#149]
Using the `serviceAccountJson` with environment variable or tilde in the path is not possible.

**Example Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@7406d2c7a1db943b737d959bdefdd7f6d9731f99
  with:
    serviceAccountJson: '$HOME/.private_keys/key.json'
    ...
```

**Results in**

```
...
Run r0adkll/upload-google-play@7406d2c7a1db943b737d959bdefdd7f6d9731f99
Error: The file at $HOME/.private_keys/key.json does not exist, or it is not a file. ENOENT: no such file or directory, lstat '/home/runner/work/toolbox/toolbox/$HOME'
```

**Expected**

Tild and variables should've been expanded and file should be located normally.

**Comment by boswelja** [comment]
This is an interesting one. Typically GH Actions handles this for us, but I guess since it is part of a fully-formed string, it does not.
I'm retagging this as a feature request :)

**Comment by milis92** [comment]
For this to work, you have to use the YAML variable expansion instead of shell expansion.
#### In your case, this would look like:
```
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: ${{ env.HOME }}/.private_keys/key.json'
    ...
```
[Here](https://github.com/orgs/community/discussions/25850) is detailed explanation why this works, but TLDR; yaml is not evaluated under the shell context so you can use shell variable expansion.
