### ISSUE TITLE
Invalid status provided! Must be one of 'completed', 'inProgress', 'halted', 'draft'. Got 

### ISSUE THREAD

**Issue by mhernand40** [r0adkll/upload-google-play#153]
**Describe the bug**
Just updated from 1.0.18 to 1.0.19 where the only thing that has changed in my configuration was the `v1.0.18` -> `v1.0.19`. However, I am seeing the following error when the workflow is run:
```
Invalid status provided! Must be one of 'completed', 'inProgress', 'halted', 'draft'. Got 
```

I've never had to specify the status property in the YML and per the README, it seems that has a default value that gets resolved if it is not specified.

**Workflow Step Configuration**

```yml
- name: Deploy to Play Store
  uses: r0adkll/upload-google-play@v1.0.19
  with:
    serviceAccountJsonPlainText: ${{ ***** }}
    packageName: *****
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: *****
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
