### ISSUE TITLE
Support for node v16

### ISSUE THREAD

**Issue by lsalehar** [r0adkll/upload-google-play#156]
**Describe the bug**
When the action is run the following warning is displayed in workflow summary:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: r0adkll/upload-google-play`

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
     ...
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
