### ISSUE TITLE
Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.

### ISSUE THREAD

**Issue by hemant1996** [r0adkll/upload-google-play#160]
**Describe the bug**
Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.

**Workflow Step Configuration**

```name: Deploy App CI

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          npm install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Deploy to Play Store (BETA)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.myrasoi
          releaseFile: ${{steps.sign_app.outputs.signedReleaseFile}}
          inAppUpdatePriority: 3
          whatsNewDirectory: android/release-notes/
          changesNotSentForReview: false
          status: completed
```

**Comment by boswelja** [comment]
I suspect this error is coming from Google Play. If that's the case, there's nothing we can do. You need to do a release with `changesNotSentForReview` set to true (usually the first time you try to publish an app, subsequent uploads don't require this)

**Comment by JElgar** [comment]
I've been getting the same error response when running with `changesNotSentForReview` set to true
```
    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
        packageName: com.some.app
        releaseFiles: some.aab
        track: beta
        status: completed
        changesNotSentForReview: true
```
Response
```
##[error***Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.
```

Am I doing something wrong/is this a google play issue or is it possible the parameter not getting propagated to the request?

**Comment by JElgar** [comment]
Ah I am getting the following warning so its almost definitely something I'm doing wrong
```
##[warning***Unexpected input(s) 'changesNotSentForReview', valid inputs are ['serviceAccountJson', 'serviceAccountJsonPlainText', 'packageName', 'releaseFile', 'releaseFiles', 'releaseName', 'track', 'inAppUpdatePriority', 'userFraction', 'status', 'whatsNewDirectory', 'mappingFile'***
```

**Comment by boswelja** [comment]
@JElgar please do not use the `v1` tag, it is known to be horribly out of date. In your case it doesn't actually support changesNotSentForReview

**Comment by rokasAt10speed** [comment]
```
uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ***
          packageName: ***
          releaseFiles: ***/app-release.aab
          track: internal
          changesNotSentForReview: true
          status: completed
```
And getting this result

<img width="945" alt="SCR-20230201-ito" src="https://user-images.githubusercontent.com/114087573/216034285-f6f15ef1-7419-41f4-a209-db7e8837e448.png">
