### ISSUE TITLE
Bug: releaseFile input does not work

### ISSUE THREAD

**Issue by gegana** [r0adkll/upload-google-play#163]
**Describe the bug**
First off, I understand that `releaseFile` input is being deprecated. Nonetheless, it continues to be supported in version 1.0.19, and users get a warning message when they are still using it to switch to the new `releaseFiles` input.

The problem is in these lines of code:
https://github.com/r0adkll/upload-google-play/blob/b9dc4464a604e12a040abf6a883d7cf05100a64e/src/main.ts#L12-L15

You can see that while releaseFile is being set as an input, releaseFiles gets defaulted to an empty array if blank. 

Then in this line of code, the inputs get validated but you'll never run into the 2nd case because releaseFiles is always defined.
https://github.com/r0adkll/upload-google-play/blob/b9dc4464a604e12a040abf6a883d7cf05100a64e/src/main.ts#L54

It will then fail here
https://github.com/r0adkll/upload-google-play/blob/b9dc4464a604e12a040abf6a883d7cf05100a64e/src/input-validation.ts#L52

Because releaseFiles is defaulted to empty array, we get this error message with no file names
![image](https://user-images.githubusercontent.com/1734059/206200423-c6a5aa14-6c9f-47d3-b7bd-48d897402747.png)

**Solution**
Solution is to just use the releaseFiles since releaseFile is being deprecated anyhow, but I thought I should file this report anyways in case someone else stumbled on the same issue.

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: production
    whatsNewDirectory: distribution/whatsnew/
    mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
