### ISSUE TITLE
Please update action so it is not using deprecated techniques anymore

### ISSUE THREAD

**Issue by jopmiddelkamp** [r0adkll/upload-google-play#169]
**Describe the bug**
I'm getting these warnings on build.

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: r0adkll/upload-google-play@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="943" alt="image" src="https://user-images.githubusercontent.com/1774351/212663529-5cfcd4af-bc52-47b8-9a6d-83846f6e0e35.png">

**Workflow Step Configuration**

```yml
      # Upload the production release to the internal test track on Google Play Store.
      - name: Release APPBUNDLE to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.play_store_gservice_account }}
          releaseFiles: ${{ inputs.app-dir }}/build/app/outputs/bundle/${{ inputs.environment }}Release/app-${{ inputs.environment }}-release.aab
          status: draft
          track: internal
          packageName: ${{ inputs.packageName }}
          changesNotSentForReview: true
```

**Step Debugging**

Just run it and you'll see the warnings as well.
