### ISSUE TITLE
Add documentation for publishing to form factor tracks

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [r0adkll/upload-google-play#170]
**Describe the bug**
There is an internal test track(default play store track) but I get the following error:
`
Track "internal" could not be found
 `

**Workflow Step Configuration**

```yml
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.playstoretoken }}
          packageName: com.something.app
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: halted
```

**Step Debugging**

```
Run r0adkll/upload-google-play@v1
Creating a new Edit for this release
Validating track 'internal'
Error: Track "internal" could not be found 
```
