### ISSUE TITLE
Github action isn't finishing.

### ISSUE THREAD

**Issue by GMetaxakis** [r0adkll/upload-google-play#172]
**Describe the bug**
Github action isn't finishing.

The upload is happening without any issue, but the github action runs forever.

**Workflow Step Configuration**

```yml
      - name: 'GPlay deployment'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: package
          releaseFiles: app/build/outputs/bundle/release/production.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          track: alpha
          status: draft
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
