### ISSUE TITLE
Error: The incoming JSON object does not contain a client_email field

### ISSUE THREAD

**Issue by adi9090** [r0adkll/upload-google-play#176]
**The incoming JSON object does not contain a client_email field**
We are getting error: The incoming JSON object does not contain a client_email field when publishing a release to a PlayStore.
This GitHub action was not changed at all and it worked without an issue.

What I've found is that this issue is introduced in firebase-tool library in version 7.0.2 and it has been fixed in 7.2.0. I'm not sure if here we are using this library or which version of it.

https://github.com/firebase/firebase-tools/issues/1451

**Workflow Step Configuration**

```yml
      - name: Deploy to PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName:  ${{ env.application_id }}
          releaseFiles: ${{ env.output_directory }}/app-release.aab
          mappingFile: ${{ env.output_directory }}/mapping/mapping.txt
          track: ${{ github.event.inputs.release_track }}
          status: ${{ github.event.inputs.release_status }}
          releaseName: ${{ github.event.inputs.version_name }}
```
