### ISSUE TITLE
Error uploading release

### ISSUE THREAD

**Issue by KesWalker** [r0adkll/upload-google-play#177]
**Describe the bug**
There was an error uploading to play console:

`Error: request to https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/uk.co.explorer/edits/02233973888706731093/bundles?uploadType=media failed, reason: read ECONNRESET
`

**Workflow Step Configuration**

```yml
  with:
    serviceAccountJsonPlainText:           ***
    packageName: uk.co.explorer
    releaseFiles: app/build/outputs/bundle/release/app-release.aab
    track: internal
    changesNotSentForReview: true
    inAppUpdatePriority: 0
    status: completed
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
