### ISSUE TITLE
Uploading unsigned bundles

### ISSUE THREAD

**Issue by tassilo-posegga** [r0adkll/upload-google-play#178]
**Describe the bug**
I am trying to upload a bundle which is not signed, as we have App signing enabled in Google Play console. The workflow error:
`Error: The Android App Bundle was not signed. Please sign the bundle using jarsigner.`

**Workflow Step Configuration**

```yml
      - name: Bundle release
        uses: gradle/gradle-build-action@v2.1.7
        with:
          gradle-version: wrapper
          arguments: app:bundleMskUsRelease

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_API_CREDENTIALS }}
          packageName: com.kaiahealth.app
          releaseFiles: app/build/outputs/bundle/mskUsRelease/app-mskUs-release.aab
          track: internal
          status: draft
          mappingFile: app/build/outputs/mapping/mskUsRelease/mapping.txt
```
