### ISSUE TITLE
Creating draft release halts staged rollout of previous version

### ISSUE THREAD

**Issue by charliealbright** [r0adkll/upload-google-play#179]
**Describe the bug**
I just started using this Action in a project and noticed a strange issue (or side-affect?). When publishing a new release draft using the Action, any in-progress releases which are not fully rolled out are halted. For example, let's say version 1 of an app is currently rolled out to 10% of users. If I use this action to make a draft release for version 2, the in-progress rollout for version 1 is halted and has to be manually resumed in Google Play Console. 

Ideally, any in-progress releases should be unaffected when creating a new draft.

I'm not sure if this is an issue with this action specifically to be honest, it very well might be an inherent behavior from Google Play's APIs - but I still wanted to make this report in case there's anything to be done from the Action's side.

**Workflow Step Configuration**

```yml
- name: Publish Draft Release (Prod)
  id: publishGooglePlayProd
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    packageName: ${{ PACKAGE }}
    releaseFiles: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab
    track: production
    status: draft
    mappingFile: ${{ github.workspace }}/app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

Didn't enable this flag since there's not necessarily a debuggable issue per-se in this report.
