### ISSUE TITLE
Socket Hangup: https://www.googleapis.com/upload/androidpublisher/v3/applications/ ... /uploadType=media failed

### ISSUE THREAD

**Issue by nirmalhk7** [r0adkll/upload-google-play#18]
I realise that an issue on this same problem was made and resolved previously, but even after incorporating those suggestions, my build isn't uploading to Play Console. I get the error: 
`##[error]request to https://www.googleapis.com/upload/androidpublisher/v3/applications/com.nirmalhk7.collegego/edits/16958456934720867488/bundles?uploadType=media failed, reason: socket hang up`

Here is my CI code:
```
name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository2
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Read project version code
      id: read_property_code
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './app/version.properties'
        property: 'version.code'
    - name: Read project version name
      id: read_property_name
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './app/version.properties'
        property: 'version.name'
    # - name: Run Unit Test
    #   id: tests
    #   run: ./gradlew test
    - name: Build AAB
      id: buildRelease
      run: ./gradlew bundleRelease
    - name: Sign AAB
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.KEYSTORE_V2 }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - name: Upload AAB
      id: uploadArtifact
      uses: actions/upload-artifact@v1
      with:
          name: appBundle
          path: app/build/outputs/bundle/release/app-release.aab
  
  deploy:
    name: Deploy Android App
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Retreive artifacts from Build stage
      uses: actions/download-artifact@v2
      with:
        name: appBundle
        path: app/build/outputs/bundle/release/app-release.aab
    - name: List Production Files
      run: ls app/build/outputs/bundle/release
    - name: Deploy to Play Store (PRODUCTION)
      id: deploy
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: com.nirmalhk7.collegego
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: production
```

Every stage in both jobs are able to run without errors. I used the List Production File stage to verify whether my file location is correct or not.
Here's the output for the last two stages of last jobs:
```
List Production Files
app-release.aab
Run ls app/build/outputs/bundle/release
  ls app/build/outputs/bundle/release
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
app-release.aab
```
```
  Deploy to Play Store (PRODUCTION)- 4m 1s
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: service_account.json
    packageName: com.nirmalhk7.collegego
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: production
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
##[error]request to https://www.googleapis.com/upload/androidpublisher/v3/applications/com.nirmalhk7.collegego/edits/02478717223293763578/bundles?uploadType=media failed, reason: socket hang up

```
