### ISSUE TITLE
Unable to find any release file matching app/release/app-release.aab

### ISSUE THREAD

**Issue by RingoMckraken** [r0adkll/upload-google-play#181]
I have verified that the app bundle exists in this directory and in my yaml config I've set releaseFiles to this path. Is there something I'm missing here or it there a directory that I need to put in there or file permission or something?

**Comment by mafreud** [comment]
same issue.

**Comment by mafreud** [comment]
When I switched to alpha, beta track, a build was available. Internal Sharing did not work.

**Comment by RingoMckraken** [comment]
So alpha and beta track did work correctly?

**Comment by RingoMckraken** [comment]
Strange I just tested with alpha and got the same error.

**Comment by mafreud** [comment]
Ok, did you check the permission of service account? I suppose you set service-account.json for this actions.

**Comment by RingoMckraken** [comment]
i uploaded the plaintext of the my service account json file into an github env variable.

**Comment by gautamsuranipromact** [comment]
Have you got any solution?

**Comment by gautamsuranipromact** [comment]
Can you please share your pipeline code?

**Comment by mafreud** [comment]
```yaml
      - name: Deploy to Play Store (Alpha)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./android/service-account-key.json
          packageName: sample.packageName
          ## I'm using this actions for Flutter.
          releaseFiles: ./build/app/outputs/bundle/release/app-release.aab
          track: alpha
          status: draft
```

**Comment by boswelja** [comment]
This seems like a configuration issue, I will mark this as invalid and, pending no further activity, close it.

**Comment by ashishcors** [comment]
Hey @RingoMckraken and everyone else facing this issue,

I encountered the same problem and managed to resolve it. I found that specifying `working-directory: ./app` in the GitHub Action job was the reason. Even though the app-release.aab was in the correct directory relative to ./app, the upload action needs the full file path starting from the root, including the working-directory in releaseFiles.

Note: Ideally, this shouldn't be the case. The action should be able to respect the working-directory and not require us to specify the full path. It would be great if this could be looked into for future updates.

Hope this helps!

**Comment by emilioizzo6** [comment]
@ashishcors where did yoyu put the `working-directory: ./app`? in the specific step?

**Comment by ashishcors** [comment]
No, It was added in the job. Here's how my yaml file looked like.

```
  build_and_publish: 
     runs-on: ubuntu-latest 
     defaults: 
       run: 
         working-directory: ./my-flutter-app 
  
    steps:
       # ...other build steps

       # confirmed that the file exists at location
       - name: List contents of release directory 
         run: ls -al build/app/outputs/bundle/release/
  
       - name: Publish to Google Play 
         uses: r0adkll/upload-google-play@v1 
         with: 
           serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_JSON }} 
           packageName: com.example.package 
           releaseFiles: my-flutter-app/build/app/outputs/bundle/release/app-release.aab 
           track: internal
```
