### ISSUE TITLE
How to upload app to a Closed testing track?

### ISSUE THREAD

**Issue by mikamikaWolt** [r0adkll/upload-google-play#185]
Hey!

I can easily upload my app to the Internal testing group with
```
- name: Deploy android production release to Google Play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.MY_ACCOUNT }}
          packageName: com.my.app
          releaseFile: build/app/outputs/bundle/myApp.aab
          track: internal
          mappingFile: build/app/outputs/mapping/mapping.txt
```

But how to upload the app to the Closed testing group?
I have created a new track in Closed testing with the name "MyAppClosed".
I tried to set track value in the GHA step like
`track: MyAppClosed`
or
`track: Closed testing - MyAppClosed` (page name in the Closed testing)
But I am getting the error "Track could not be found".

Could you help how to upload my app to Closed beta track, please?
