### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by xudule** [r0adkll/upload-google-play#186]
**Describe the bug**
When action is running, there is this unknow error showed in the log: "Error: Unknown error occurred.".

**Workflow Step Configuration**

```yml
- name: Upload to Play Console
  if: startsWith(github.ref, 'refs/tags/android')
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    packageName: <com.example.app>
    releaseFiles: build/app/outputs/bundle/release/app-release.aab
    track: internal
```

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging). However, there is nothing more than that message unknown error

> Run r0adkll/upload-google-play@v1
  with:
    packageName: <com.example.app>
    releaseFiles: build/app/outputs/bundle/release/app-release.aab
    track: internal
    inAppUpdatePriority: 0
    status: completed
    changesNotSentForReview: false
  env:
    PROPERTIES_PATH: ./android/key.properties
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.7.12-x64
    PUB_CACHE: /home/runner/.pub-cache
Error: Unknown error occurred.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Upload to Play Console

I took a look at the code and it seems that the message error is here: https://github.com/r0adkll/upload-google-play/blob/d17e3fc7456ff0666a31bbdfce64b9aec6b79a94/src/main.ts#L92

- [x] I have enable API access in google play console
