### ISSUE TITLE
Public AAB failed with error

### ISSUE THREAD

**Issue by hivenet-sathishgadde-osi** [r0adkll/upload-google-play#188]
**Describe the bug**
Am randomly facing the below error:
<img width="1066" alt="image" src="https://github.com/r0adkll/upload-google-play/assets/121420571/a56870ac-6dfb-41b5-b43a-7943f9d29343">

**Workflow Step Configuration**
``

```yml
      - name: Publish AAB to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.android.demo.preprod
          releaseFiles: ./apps/***/build/outputs/bundle/preprod/***-preprod.aab
          track: ${{ env.RELEASE_TRACK }}
          releaseName: ${{ env.VERSION_CODE }} (${{ env.VERSION_NAME }})
          inAppUpdatePriority: ${{ env.IN_APP_UPDATE_PRIORITY }}
```

**Step Debugging**

At the moment, I don't have the debug logs. I'll share them with you once I've collected this information from the workflow.

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

**Comment by Nek-12** [comment]
Experiencing this issue too

**Comment by lsalehar** [comment]
We're experiencing this as well. We tried changing the Service Account JSON, but the issue persists.

**Comment by joao-albach** [comment]
Same here

**Comment by boswelja** [comment]
By "randomly", do you mean it sometimes fails and sometimes succeeds?

**Comment by aabiryukov** [comment]
It's looks like the issue is on Google side. The same error occurs when publishing via fastlane: https://github.com/fastlane/fastlane/issues/21507

**Comment by boswelja** [comment]
Interesting, we can give that a go

**Comment by boswelja** [comment]
> @r0adkll From [the issue](https://github.com/fastlane/fastlane/issues/21507#issuecomment-1720229951) shared by @aabiryukov, it seems the fix is to update the android publisher url to `"https://androidpublisher.googleapis.com/"` in this file: https://github.com/r0adkll/upload-google-play/blob/master/src/edits.ts#L52

It's worth mentioning Fastlane developers confirmed the URL is not an issue, and all they could do was optimize network calls so it had less chances to happen

**Comment by boswelja** [comment]
If anyone is interested in testing this, please try using the branch for #190 in your action. **Note that this error is random, and a one-shot run is not enough to say whether this has helped**

**Comment by msgivaldo** [comment]
Changing to `attempt-fix-for-random-google-issue` I got an error 

<img width="670" alt="image" src="https://github.com/r0adkll/upload-google-play/assets/119754964/314fc73b-b931-4f70-be30-b7058c7d68e3">

**Comment by boswelja** [comment]
> Changing to `attempt-fix-for-random-google-issue` I got an error 
> 
> <img width="670" alt="image" src="https://github.com/r0adkll/upload-google-play/assets/119754964/314fc73b-b931-4f70-be30-b7058c7d68e3">

Thanks for trying it! Does it consistently give that error? If so, we can probably discard the change

**Comment by menssen** [comment]
Same "Invalid Credentials" error from the attempt-fix... branch, if you want one more data point.

**Comment by omar-alshyokh** [comment]
I have the same error just when I'm trying to use **`whatsNewDirectory`**, and it works properly when i removed it.
```
      - name: Publish To Store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: android/service_account.json
          packageName: '....'
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          whatsNewDirectory: whatsnew
```

**Comment by msgivaldo** [comment]
I've tried v1 tag without whatsNewDirectory and works as expected too

<img width="627" alt="image" src="https://github.com/r0adkll/upload-google-play/assets/119754964/f8c4aae6-b5df-49b3-9bdc-3dd2ad5c5090">

**Comment by Miiite** [comment]
I don't think the whatsNewDirectory really affects anything. This is my task

```yaml
 - name: upload PROD package to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT_JSON }}
          packageName: io.thering.app
          releaseFiles: app-release.aab
          releaseName: ${{ inputs.tag }}
          track: internal
          status: inProgress
```
And I end up having the same issue everyone is describing (which has occured every time I launched a build from this morning)

**Comment by Fudal** [comment]
> I've tried v1 tag without whatsNewDirectory and works as expected too
> 
> ```
> - name: Deploy to Play Store
>   id: deploy
>   uses: r0adkll/upload-google-play@v1
>   with:
>     serviceAccountJson: service_account.json
>     packageName: dev.givaldo.carspecs
>     releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
>     mappingFile: android/app/build/outputs/mapping/release/mapping.txt
>     track: beta
> ```
> 
> <img alt="image" width="627" src="https://user-images.githubusercontent.com/119754964/268655234-f8c4aae6-b5df-49b3-9bdc-3dd2ad5c5090.png">

It helped nie too.

**Comment by Nek-12** [comment]
I'm not using the whatsNew property and still experiencing  this issue. I'm using 1.1.1 though

**Comment by armanso** [comment]
```
      - name: upload artifact to playstore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.a*******e.${{ matrix.flavors }}_app

          releaseFiles: build/app/outputs/bundle/${{ matrix.flavors }}Release/app-${{ matrix.flavors }}-release.aab
          status: draft
          mappingFile: build/app/outputs/mapping/${{ matrix.flavors }}Release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/${{ matrix.flavors }}Release/out/lib
```

We do face the same issue.
