### ISSUE TITLE
Error: 'userFraction' must be between 0 and 1! Got 1

### ISSUE THREAD

**Issue by MartenM** [r0adkll/upload-google-play#194]
**Describe the bug**
When deploying with a user-fraction of `1.0` an error is thrown.

![Github action logs](https://img.martenm.nl/uSVmk)
<details>
<summary>Raw logs</summary>

```
Run r0adkll/***-google-play@v1
  with:
    serviceAccountJsonPlainText: 
    packageName: xxxx
    releaseFiles: build/app/outputs/bundle/release/app-release.aab
    track: internal
    status: completed
    inAppUpdatePriority: 2
    userFraction: 1
    whatsNewDirectory: distribution/changelog
    changesNotSentForReview: false
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.10.5-x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/stable-3.10.5-x64/.pub-cache
Error: 'userFraction' must be between 0 and 1! Got 1
```

</details>

**Workflow Step Configuration**

```yml
      # Build and deploy 🚀
      - name: Deploy to google play console (Play Store)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CONSOLE_JSON }}
          packageName: xxx
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: ${{ github.event.inputs.release-track }}
          status: completed
          inAppUpdatePriority: 2
          userFraction: 1.0
          whatsNewDirectory: distribution/changelog
```

**Step Debugging**
Not really any debug steps. Any help would be appreciated!
