### ISSUE TITLE
releasing to Prod

### ISSUE THREAD

**Issue by saintmalik** [r0adkll/upload-google-play#196]
**Describe the bug**
I am trying to release to production track and the status to be draft, but I have been getting this error, Only releases with status draft may be created on draft app., I also removed the status at some point but the error never changed.

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: service_account.json
    packageName: com.example
    releaseFiles: android/app/build/outputs/bundle/release/app-release-signed.aab
    track: production
    status: draft
```
