### ISSUE TITLE
When userFraction is not set, PlayStore console sets the rollout percentage to 1%

### ISSUE THREAD

**Issue by rafaelvcaetano** [r0adkll/upload-google-play#200]
**Describe the bug**
When the `userFraction` parameter is not set, the release overview in PlayStore shows a default rollout percentage of 1% instead of the expected 100% (see image below).

![image](https://github.com/r0adkll/upload-google-play/assets/9086379/ea30743a-fc98-4eb5-8313-0133dfb83a85)

**Workflow Step Configuration**

```yml
- name: Create Play Store Release
  uses: r0adkll/upload-google-play@v1.1.2
  with:
    serviceAccountJsonPlainText: ${{ <<REDACTED>> }}
    packageName: <<REDACTED>>
    releaseName: ${{ steps.release_params.outputs.VERSION }}
    releaseFiles: <<REDACTED>>
    track: beta
    inAppUpdatePriority: 2
    status: draft
    whatsNewDirectory: <<REDACTED>>
    mappingFile: <<REDACTED>>
    debugSymbols: <<REDACTED>>
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
