### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by mallhar** [r0adkll/upload-google-play#218]
**Describe the bug**
"Unknown error occurred." No additional information provided by the error.
Publishing app to Google Play for the first time.

```
Run r0adkll/upload-google-play@v1
  with:
    packageName: <REDACTED>
    releaseFiles: ./my_app/app/build/app/outputs/bundle/productionRelease/app-production-release.aab
    track: qa
    inAppUpdatePriority: 0
    status: completed
    changesNotSentForReview: false
  env:
    PACKAGE_NAME: <REDACTED>
    JAVA_VERSION: 17
    FLUTTER_VERSION: [3](https://github.com/mallhar/my_app_be/actions/runs/8953346119/job/24591750256#step:12:3).19.6
    APP_DIR: my_app/app
    KEY_PROPS_PATH: android/key.properties
    KEYSTORE_KEY_PATH: android/app/upload-keystore.jks
    GOOGLE_SERVICES_JSON_PATH: android/app/google-services.json
    GCP_SERVICE_ACCOUNT_KEY_PATH: android/service-account.json
    AAB_PATH: ./my_app/app/build/app/outputs/bundle/productionRelease/app-production-release.aab
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x6[4]
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.19.6-x64
    PUB_CACHE: /home/runner/.pub-cache
Error: Unknown error occurred.
```

**Workflow Step Configuration**

```yml
      - name: 🚀 Deploy to Play Store
        id: deploy-play-store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_PATH }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_PATH }}
          track: ${{inputs.google_play_track}}
```
