### ISSUE TITLE
Unable to find any release file matching

### ISSUE THREAD

**Issue by tuyen-vuduc** [r0adkll/upload-google-play#221]
**Describe the bug**
I am trying to set up a GitHub Action workflow to publish my sample Android app to Play Store.
However, I faced error of `Unable to find any release file matching`

![image](https://github.com/r0adkll/upload-google-play/assets/3112460/d6f79b5a-4e4a-4ac9-8044-d4542e67edcb)

**Workflow Step Configuration**

The workflow can be found here 

https://github.com/tuyen-vuduc/chick-and-paddy-dotnet-maui/blob/main/.github/workflows/android.yml

**Step Debugging**

- [x ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

**Comment by boswelja** [comment]
You need to point the action to your signed release apk/aab

**Comment by tuyen-vuduc** [comment]
@boswelja  Have you checked out my YAML?

My steps are
1/ Build and upload AAB to artifact folder
2/ Download the artifact to current workspace
   a. I also use `ls` to ensure the file downloaded well
3/ Upload the downloaded AAB via the action

**Comment by boswelja** [comment]
> @boswelja Have you checked out my YAML?
> 
> My steps are 1/ Build and upload AAB to artifact folder 2/ Download the artifact to current workspace a. I also use `ls` to ensure the file downloaded well 3/ Upload the downloaded AAB via the action

Did you try wrapping your `releaseFiles` in quotes? According to your run output, it's not checking in any folder.

**Comment by brux88** [comment]
i have the same problem

**Comment by Ramo-Y** [comment]
I had the same issue and solved it by surrounding the path with quotes, it worked on the Ubuntu image, but not on Windows.

**Comment by CRoederTND** [comment]
Anyone found a solution? I can verify the file is there, but I get the same message.

**Comment by Ramo-Y** [comment]
I also had problems uploading because the setup was incomplete. The privacy policy and data safety information were missing, but after adding them it worked. Go to the Developer Console, Dashboard, and check if you have set everything under “LET US KNOW ABOUT THE CONTENT OF YOUR APP”.

**Comment by CRoederTND** [comment]
I solved it by replacing '\' with '/'

**Comment by CRoederTND** [comment]
> have the same issue here

Try replacing \\ with /

**Comment by fadlurahmanfdev** [comment]
> > have the same issue here
> 
> Try replacing \ with /

still give me an error @CRoederTND 

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/3f35c875-06df-47c9-bb88-97ba3a1be6e7">

**Comment by CRoederTND** [comment]
@fadlurahmanfdev are you sure the file is there?

**Comment by fadlurahmanfdev** [comment]
> @fadlurahmanfdev are you sure the file is there?

sure, I already check the folder, and it contain my aab file

**Comment by fadlurahmanfdev** [comment]
> @fadlurahmanfdev are you sure the file is there?

sure @CRoederTND , I already check the directory using ls command & the file is there

<img width="469" alt="image" src="https://github.com/user-attachments/assets/da84a859-a45e-4277-9f73-11d91ac7729f">
<img width="553" alt="image" src="https://github.com/user-attachments/assets/ee6139b5-3ce4-451a-bb0f-b91bd2d82730">
<img width="952" alt="image" src="https://github.com/user-attachments/assets/d11e9a42-2b3e-4587-a12c-dbd4b2825a38">

**Comment by Surkhojb** [comment]
Hi there,

I also have the same issue here.

I am getting the apk from the path and saving in a variable. The variable is getting the .aab file without problem. but once we pass this variable to the action it fails.

```
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJson: ***
    packageName: our.current.package
    releaseFile: ./artifacts/App-Release-108000701.aab
    track: qa
    inAppUpdatePriority: 0
    status: completed
    changesNotSentForReview: false
  env:
    DOWNLOAD_APK_PATH: ./artifacts/App-Release-150800001.aab
```

Here is the job I am using to deploy the .aab to stores

```
deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Debug Build from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundle-artifact
          path: ./artifacts/

      - name: Get Path to file
        run: |
          echo "DOWNLOAD_APK_PATH=$(find ./artifacts/*.aab)" >> $GITHUB_ENV

      - name: Upload AAB to Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          packageName: our.current.package
          releaseFile: ${{env.DOWNLOAD_APK_PATH}}
          track: qa

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
```

Any solution / workaround? 

Previously I thought it was because I was running on Windows runner, but after changing to Ubuntu runner still having same error

**Comment by edwinnyawoli** [comment]
From the docs of [actions/upload-artifact@v4](https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives), your signed apk/app bundle is uploaded as a zip file. When you use the [actions/download-artifact@v4](https://github.com/actions/download-artifact?tab=readme-ov-file#inputs), the artifact is downloaded into a folder with the name you specified on the upload action (unless you specify otherwise).

So you can use something like

````yaml
build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build appbundle
    
      - name: Upload App bundle to Releases
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab

  deploy_android:
    name: Deploy Android Build

    needs: build_android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get Android Build from artifacts
      uses: actions/download-artifact@v4

    - name: Release Build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
        packageName: com.xyz.app
        releaseFiles: app-release/app-release.aab
        track: internal
        status: completed
````

**Comment by CSkoubo** [comment]
On my gh action it was because of \ instead of /.

Do also note that the upload action is using fast-glob to find the file. This is case sensitive.

**Comment by helderman** [comment]
One possible explanation for this error is specifying the wrong file path. This may seem obvious, but I had this weird case where everything worked fine, until I added a path to the upload-artifact step. Sharing it here in case somebody happens to run into the same problem.

Initially, the ZIP file contained 3 folders:
```
- name: Upload artifacts
  uses: actions/upload-artifact@v4
  with:
    name: android-build
    path: |
      app/build/outputs/
      app/build/reports/
      app/build/test-results/
```

Upload-artifact is smart enough to prune the common base folder. The resulting ZIP file looks like:
- outputs/
- reports/
- test-results/

To restore the same folder tree, you must download/unzip it into that common base folder:
```
- name: Download build artifact
  uses: actions/download-artifact@v4
  with:
    name: android-build
    path: app/build/
```

Trouble started when I decided to add lint's report to the artifact. This is in a completely different folder:
```
- name: Upload artifacts
  uses: actions/upload-artifact@v4
  with:
    name: android-build
    path: |
      app/build/outputs/
      app/build/reports/
      app/build/test-results/
      build/reports/
```

Now the common base folder is the repo's root folder. The ZIP file changes to:
- app/build/outputs/
- app/build/reports/
- app/build/test-results/
- build/reports/

The original download step resulted in a completely different output folder:
- app/build/app/build/artifacts/outputs/

Changing the download folder to the new common base folder (i.e., repo's root) fixed the problem:
```
- name: Download build artifact
  uses: actions/download-artifact@v4
  with:
    name: android-build
    path: ./
```
