### ISSUE TITLE
Unable to publish an aab in Internal Testing track with status completed

### ISSUE THREAD

**Issue by kgouraw** [r0adkll/upload-google-play#222]
**Describe the bug**
I used to publish an android app bundle in the Internal Testing track with my first app version 1.1
When I changed my app version to 1.2, it started throwing an error: Internal error encountered.

Expectation: It should work with status: completed without any issue.
PS: Have not changed service account JSON key

**Workflow Step Configuration**

```yml
- name: Deploy Internal
  uses: r0adkll/upload-google-play@v1.1.3
  with:
    serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    status: completed
    track: internal
    inAppUpdatePriority: 0
    changesNotSentForReview: false  
```
Error:

Creating a new Edit for this release
Validating track 'internal'
Uploading app/build/outputs/bundle/release/app-release.aab
##[debug][00653319132042375284, packageName= ****] Uploading App Bundle @
app/build/outputs/bundle/release/app-release.aab
Error: Internal error encountered.
##[debug]Node Action run completed with exit code 1
##[debug]GOOGLE_APPLICATION_CREDENTIALS='service_account.json'
##[debug]Finished: run
##[debug]Finishing: Upload Artifact to Google Play

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
