### ISSUE TITLE
Deploy WearOS applicaion

### ISSUE THREAD

**Issue by zimml** [r0adkll/upload-google-play#235]
**Describe the bug**
I'm trying to deploy a WearOS application but I get error:
`Error: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.
`
My application is composed of a Mobile application (which deploys correctly) and a WearOS application which reports this error. 

Is this a known limitation ? Is there something special to configure to send the AAB to WearOS instead of Mobile OS ? 

**Workflow Step Configuration**

Here is the yml I used to upload.

```yml
    - name: Deploy Google play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: foo.io
        releaseFiles: "${{ runner.workspace }}/output/${{ matrix.project }}.aab"
        track: internal
```
