### ISSUE TITLE
This edit has already been successfully committed, please create a new Edit.

### ISSUE THREAD

**Issue by lolevsky** [r0adkll/upload-google-play#48]
I had setup google play upload in this way:
```
- uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "my.package.name"
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: alpha
```
The upload is working, and I see the aab in google play, but I am getting an error in github actions and it fails my build:
```
Error: This edit has already been successfully committed, please create a new Edit.
```

anyone know what is wrong?

P.S. I checked the version that I am uploading is unique and incremental number, so it is newer and higher version numbers.
