### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by Drzaln** [r0adkll/upload-google-play#60]
it always say `package not found` but my package name already same as the applicationId at `app/build.gradle`

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT }}
    packageName: com.rnbola
    releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
    track: beta
    inAppUpdatePriority: 3
    userFraction: 0.5
    whatsNewDirectory: android/release-notes/
```

**Step Debugging**

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

[This is my failed action](https://github.com/Drzaln/react-native-football/runs/1795326466?check_suite_focus=true)

**Comment by kisakyegordon** [comment]
Am getting the same issue and its frustrating

**Comment by madhank93** [comment]
Me too getting the same error.

**Comment by Warns** [comment]
@r0adkll can you please elaborate how to use the `whatsNewDirectory`

My workflow also is failing with the following error;
`Error: Unable to find 'whatsnew' directory @ android/release-notes/`

The related part in my workflow;
```
      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APPBUNDLE
          path: build/app/outputs/bundle/release/app-release.aab
  release_internal:
    name: Release Artifacts to internal track
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get APPBUNDLE from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: APPBUNDLE
      - name: Release APPBUNDLE to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GPLAY_CONFIG_JSON }}
          packageName: com.sociallme.app
          releaseFiles: app-release.aab
          track: internal
          whatsNewDirectory: android/release-notes/
```
I'm unsure what to provide with the naming `whatsnew` or what is it expecting. Thanks
