### ISSUE TITLE
Running it locally leaves a service account file.

### ISSUE THREAD

**Issue by tangent-q** [r0adkll/upload-google-play#61]
**Describe the bug**
I am running this locally using [act](https://github.com/nektos/act) and everything works fine, but after finishing the publish, it creates a service account file in the local directory.

**Workflow Step Configuration**

```yml
# .github/workflows/publish.yml
name: "Publish Action"

on:
  push:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: in.coastalbook.app
          releaseFiles: app/release/app-release.aab
          track: internal
          inAppUpdatePriority: ${{ secrets.RELEASE_PRIORITY }}
          whatsNewDirectory: distribution/whatsnew
          # mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Run this to publish**

```
act -s SERVICE_ACCOUNT_JSON_TEXT="$(< ~/.coastalbook-playstore-publish-service-account.json)" -s RELEASE_PRIORITY --bind --directory .
```

**What happens**
- There will be a new file `serviceAccountJson.json` created in the current directory.
- I can add a cleanup step but would be nice to have it cleaned in the publish step itself. Also, the cleanup may get tricky when the publish fails.
