### ISSUE TITLE
Cannot update a published APK

### ISSUE THREAD

**Issue by kunal26das** [r0adkll/upload-google-play#64]
**Describe the bug**
Error: Error: Cannot update a published APK.
Error: Cannot update a published APK.

Need to know why I'm seeing this.

**Workflow Step Configuration**

```yml
- name: Deploy to internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: in.powerplay.android.fieldapp
          releaseFiles: powerplay/powerplay-debug.apk
          inAppUpdatePriority: 5
          userFraction: '0.99'
          track: internal
          whatsNewDirectory: whats-new
```

**Step Debugging**

- [ ] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)
