### ISSUE TITLE
Only releases with status draft may be created on draft app.

### ISSUE THREAD

**Issue by DuarteBarbosaPT** [r0adkll/upload-google-play#70]
**Describe the bug**

Can't upload to internal track
"Error: Unknown Error in Upload(Error: Only releases with status draft may be created on draft app.): Only releases with status draft may be created on draft app."

**Workflow Step Configuration**

```yml
      - uses: actions/checkout@v2
      
      - name: 'Upload to Google Play'
        uses: r0adkll/upload-google-play@fix/internal-errors
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: my.package.name
          releaseFiles: app/release/app-release.aab
          track: internal
          whatsNewDirectory: whatsNewDirectory/
          mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

Creating a new Edit for this release
Validating track 'internal'
Uploading app/release/app-release.aab
Successfully uploaded 1 artifacts
Adding 1 artifacts to release on 'internal' track
Committing the Edit
Error: Unknown Error in Upload(Error: Only releases with status draft may be created on draft app.): Only releases with status draft may be created on draft app.
