### ISSUE TITLE
Number Range for userFraction is exclusive

### ISSUE THREAD

**Issue by jbooherl** [r0adkll/upload-google-play#72]
**Describe the bug**
1.0 and 0.0 should be valid.

**Workflow Step Configuration**

```yml
      - name: Play Store Upload
        id: playstore-upload
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: |
            ${{ secrets.ANDROID_SERVICE_ACCOUNT}}
          packageName: com.some.org
          releaseFiles: android/app/build/outputs/bundle/someOrg/some-org.aab
          track: alpha
          userFraction: "1.0"
          mappingFile: android/app/build/outputs/mapping/someOrg/mapping.txt
```

**Step Debugging**
Current userFraction is <= and >= when it should be < and >.
