### ISSUE TITLE
Ability to release to more than one track in single build

### ISSUE THREAD

**Issue by richard457** [r0adkll/upload-google-play#74]
track: [beta,production] is this possible?

**Comment by amitav13** [comment]
I'm looking for this as well. This is my current non-working setup:
```
- name: Upload to Beta track on Play Store
        if: ${{ contains(env.RELEASE_VERSION, 'beta') }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: my.app
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: beta
          whatsNewDirectory: releaseNotes
          mappingFile: app/build/outputs/mapping/prodRelease/mapping.txt
      - name: Upload to Production track on Play Store
        if: ${{ contains(env.RELEASE_VERSION, 'prod') }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: my.app
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: production
          whatsNewDirectory: releaseNotes
          mappingFile: app/build/outputs/mapping/prodRelease/mapping.txt
```
This gives me an error since if I try to do a prod release with the same aab since the `versionCode` is already taken. 
Rather than a new release, we need to "promote" the release from beta to prod.
