### ISSUE TITLE
Bump version code?

### ISSUE THREAD

**Issue by xtovski** [r0adkll/upload-google-play#83]
**Describe the bug**
Version code sent to Google Play is modified, suffixed with "004"

**Workflow Step Configuration**

build.gradle:
```groovy
android {
    defaultConfig {
        applicationId "***"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1006
        versionName "1.0"
    }
}
```

ci.yml:
```yml
      - name: Deploy to Play Store (act)
        uses: r0adkll/upload-google-play@v1
        if: ${{ secrets.GOOGLE_PLAY_ACCOUNT_JSON }}
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_ACCOUNT_JSON }}
          packageName: ***
          releaseName: ci:act
          status: draft
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          inAppUpdatePriority: 1
```

**Step Debugging**

- [*] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

```text
[Manual CI Workflow/Internal Staging (act)]   💬  ::debug::Finding files android/app/build/outputs/bundle/staging/app-staging.aab
| Creating a new Edit for this release
| Validating track 'internal'
| Uploading android/app/build/outputs/bundle/staging/app-staging.aab
[Manual CI Workflow/Internal Staging (act)]   💬  ::debug::[03412890307785976261, packageName=***]: Uploading App Bundle @ android/app/build/outputs/bundle/staging/app-staging.aab
| Successfully uploaded 1 artifacts
| Adding 1 artifacts to release on 'internal' track
[Manual CI Workflow/Internal Staging (act)]   💬  ::debug::Creating Track Release for Edit(03412890307785976261) for Track(internal) with a UserFraction(undefined), Status(draft), and VersionCodes(1006004)
[Manual CI Workflow/Internal Staging (act)]   💬  ::debug::Track: [object Object]
| Committing the Edit
| Successfully committed 03412890307785976261
| Finished Uploading to the Play Store: 03412890307785976261
[Manual CI Workflow/Internal Staging (act)]   ✅  Success - Deploy to Play Store (act)
```
