### ISSUE TITLE
Execution takes too long and gets canceled

### ISSUE THREAD

**Issue by marin-marsic** [r0adkll/upload-google-play#86]
**Describe the bug**

I've been using this action to upload versions of the app to internal app sharing. Recently I've noticed that the upload action takes too long to finish executing and eventually gets terminated by the host. 

![Screenshot 2021-11-08 at 15 50 20](https://user-images.githubusercontent.com/12954958/140765672-e34865ed-b5b5-4cbb-b48f-731a0df5c4c0.png)

![Screenshot 2021-11-08 at 15 49 50](https://user-images.githubusercontent.com/12954958/140765707-fd951931-1cd3-4188-9f37-9aae0a529993.png)

**Workflow Step Configuration**

```yml
- name: Upload AppBundle to Internal App Sharing
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}
    packageName: com.***
    releaseFiles: mobile/build/outputs/bundle/internal/mobile-qa.aab
    track: internalsharing
    mappingFile: mobile/build/outputs/mapping/qa/mapping.txt
```

I didn't use debugging because it always works when I restart the job, and I didn't manage to catch it using debug mode
