### ISSUE TITLE
Track does not allow to choose other closed testing tracks 

### ISSUE THREAD

**Issue by dinisnunes1** [r0adkll/upload-google-play#91]
**Describe the bug**
Track allowed values are: `alpha`, `beta`, `internal`, `production`, `internalsharing`.
Google Play allow other types of closed testing, and we can name it as we want. 
For instance, I have a closed track on Google Play named "**Release candidate**", how to set the **track** field to Release candidate name? 
(official docs: [https://support.google.com/googleplay/android-developer/answer/9845334#create_additional_track&zippy=%2Ccreate-additional-closed-test-tracks-for-your-development-teams)](https://support.google.com/googleplay/android-developer/answer/9845334#create_additional_track&zippy=%2Ccreate-additional-closed-test-tracks-for-your-development-teams)

**Workflow Step Configuration**

```yml
- name: Deploy Production
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    releaseFile: app/build/outputs/bundle/release/app-release.aab
    track: release candidate
    whatsNewDirectory: distribution/whatsnew/
    mappingFile: app/build/outputs/mapping/release/mapping.txt
```

**Step Debugging**

- [X] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

![google-play-upload-issue](https://user-images.githubusercontent.com/12532273/147264544-6df52b5e-5661-4bdf-a7d6-73b7fbd30524.png)
