### ISSUE TITLE
Error: Unable to find 'whatsnew' directory @ distribution/

### ISSUE THREAD

**Issue by rana01645** [r0adkll/upload-google-play#92]
I set the whatsnew directory according to the documentation

Still always getting this error

Error: Unable to find 'whatsnew' directory @ distribution/

**Comment by JoelKanyi** [comment]
Was this ever solved because I am always getting the error

**Comment by rana01645** [comment]
Okay, I figure out a soltion. The first step should always checkout the current project directory
So, adding   - uses: actions/checkout@v2 this line  fixed the issue
Before
```
  deploy-play-store:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app-release.aab
      - uses: actions/download-artifact@master
        with:
          name: mapping.txt
      - uses: r0adkll/upload-google-play@v1.0.16
        name: Publish to Play Store internal test track
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.x.x
          releaseFile: app-release.aab
          track: production
          mappingFile: mapping.txt
          changesNotSentForReview: true
          whatsNewDirectory: distribution/whatsnew
```

After
```
  deploy-play-store:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: app-release.aab
      - uses: actions/download-artifact@master
        with:
          name: mapping.txt
      - uses: r0adkll/upload-google-play@v1.0.16
        name: Publish to Play Store internal test track
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.trickbd.trickbdapp
          releaseFile: app-release.aab
          track: production
          mappingFile: mapping.txt
          changesNotSentForReview: true
          whatsNewDirectory: distribution/whatsnew
```
